name: ableron-spring-boot with Spring Boot 3 and Java 17

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - run: ./gradlew test --tests '*.SpringBoot3Java17Spec'
