name: ableron-java with Java 20

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: temurin
          cache: gradle
      - run: ./gradlew test --tests '*.Java20Spec'
