name: ableron-spring-boot @ Java 17 & Spring Boot 3

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - run: ./gradlew test --tests '*.Java17SpringBoot3Spec' --info
