name: ableron-spring-boot @ Java 11 & Spring Boot 2

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - run: ./gradlew test --tests '*.Java11SpringBoot2Spec'
