name: CI

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - testClass: AbleronJavaSpec
          - testClass: AbleronSpringBoot2Spec
          - testClass: AbleronSpringBootSpec
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin
          cache: gradle
      - run: ./gradlew test --test ${{ matrix.testClass }}
