name: ableron-express @ Node.js 21 & Express 4 & CommonJS

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - run: ./gradlew test --tests '*.NodeJs21Express4CjsSpec' --debug
