name: ableron-js @ Node.js 22 using CommonJS

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - run: ./gradlew test --tests '*.NodeJs22CommonJsSpec' --info
